created create item, update item. Moved destroy method to make tests …
nvnatasha/Little-Shop pull request #27
Opened 2024-11-04 22:43 UTC by nvnatasha

In this PR:

- route and method for create item done
- route and method for update item done
- moved destroy method in items controller.

2024-11-04 22:48 UTC, wally-yawn requested changes
You'll need some sad path tests for both create and update, I think you can mimic the sad path tests James did in merchant_create_spec and merchant_update_spec

2024-11-04 22:55 UTC, wally-yawn commented
Looking at it again, looks like the items model will also need to validate the presence of those attributes and would need model tests for those, Looks like the merchant model and tests have a pattern you can follow

2024-11-05 01:18 UTC, wally-yawn approved these changes
Approve tests and error handling, new card made for model tests

2024-11-05 03:01 UTC, Jonathan-Atkins commented on app/controllers/api/v1/items_controller.rb
> +  def destroy
thanks for moving that

2024-11-05 03:03 UTC, Jonathan-Atkins approved these changes

2024-11-05 03:03 UTC, merged